# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true
    -DdeployAtEnd=true"
maven38-java11-sonar:
  image: maven:3.8.1-jdk-11-slim
  stage: build
  only:
  - master
  script:
  - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent --settings
    settings.xml deploy
  - mvn $MAVEN_CLI_OPTS sonar:sonar
  cache:
    paths:
    - ".m2/repository"
maven38-java11:
  image: maven:3.8.1-jdk-11-slim
  stage: build
  except:
  - master
  script:
  - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent --settings
    settings.xml deploy
  cache:
    paths:
    - ".m2/repository"
maven38-java16:
  image: maven:3.8.1-openjdk-16-slim
  stage: test
  script:
  - mvn $MAVEN_CLI_OPTS clean package -Dmaven.javadoc.skip=true -Djacoco.skip=true
  allow_failure: true
stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
