variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"


<<<<<<< HEAD
java8:
    image: maven:3.5.4-jdk-8-alpine
    stage: build
    script: 
      - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent --settings settings.xml deploy 
      - mvn $MAVEN_CLI_OPTS sonar:sonar
    cache:
       paths:
        - .m2/repository 

=======
>>>>>>> JAN_FIX
jars-j8:
    image: frekele/ant:1.10.1-jdk8
    stage: build
    script: 
      - ant -Drelease=NIGHTLY kth
    artifacts:
       paths:
        - dist/NIGHTLY/sat4j-kth.jar
       expire_in: 4 weeks
<<<<<<< HEAD

java7:
    image: maven:3.5.4-jdk-7-alpine
    stage: test
    script: 
      - mvn $MAVEN_CLI_OPTS clean package -Dmaven.javadoc.skip=true -Djacoco.skip=true
    allow_failure: true
    
maven36-java11:
    image: maven:3.6.1-jdk-11-slim
    stage: test
    script: 
      - mvn $MAVEN_CLI_OPTS clean package -Dmaven.javadoc.skip=true -Djacoco.skip=true
    allow_failure: true

maven36-java12:
    image: maven:3.6.1-jdk-12
    stage: test
    script:
      - mvn $MAVEN_CLI_OPTS clean package -Dmaven.javadoc.skip=true -Djacoco.skip=true
    allow_failure: true

=======
>>>>>>> JAN_FIX
